---
env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
plugins:
  - json-format
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: ["error", "always", { ignorePackages: true }]
settings:
  json/sort-package-json: standard
  json/ignore-files:
    - "**/package-lock.json"
  json/json-with-comments-files:
    - ".vscode/**"
