name: Node.js CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    types: [ labeled ]  
    
env:
  NGINX-PORT: 8080
  ARANGO-PORT: 8529
  QSERVER-PORT: 4000
  NODE-PORT: 40301
  
jobs:
  labels:
    name: Label taking off
    if: github.event.label.name == 'start_tests'
    runs-on: ubuntu-latest
    steps:
      - name: Take off label
        uses: actions/github-script@v1
        with:
          script: "github.issues.removeLabel({...context.issue, name: '${{ github.event.label.name }}' })"
  tests:
    if: github.event.label.name == 'start_tests' || github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        # disable matrix die to billing limits
        # node-version: [ 12.x, 15.x ]
        # os: [ ubuntu, macos, windows ]
        node-version: [ 14.x ]
        os: [ ubuntu ]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: cli
      - uses: actions/checkout@v2
        with:
          repository: tonlabs/ton-client-js
          path: ton-client-js

      - name: "Use Node.js: ${{ matrix.node-version }} OS: ${{matrix.os}}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore CLI
        working-directory: cli
        run: |
          npm i
          npm i -g
      - name: Run Node SE
        run:
          ton-node start
      - name: Check ports
        run: |
          nc -z -v -w1 localhost ${{ env.NGINX-PORT }}
          nc -z -v -w1 localhost ${{ env.ARANGO-PORT }}
          nc -z -v -w1 localhost ${{ env.QSERVER-PORT }}
          nc -z -v -w1 localhost ${{ env.NODE-PORT }}
      - name: Build ton-client-js/packages/core
        working-directory: ton-client-js/packages/core
        run: |
          npm i
          tsc
      - name: Build ton-client-js/packages/tests
        working-directory: ton-client-js/packages/tests
        run: |
          npm i
          tsc
      - name: Run tests
        working-directory: ton-client-js/packages/tests-node
        env:
          USE_NODE_SE: true
          TON_NETWORK_ADDRESS: http://localhost:${{ env.NGINX-PORT }}
        run: |
          npm i
          node run