name: Main workflow

on:
  push:
  workflow_dispatch:

jobs:
  build-node:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tonlabs/tonos-se

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ton-node-se/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        working-directory: ton-node-se
        run: |
          cargo build --release

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: ton_node_startup-${{ matrix.os }}
          path: |
            ton-node-se/target/release/ton_node_startup
            ton-node-se/target/release/ton_node_startup.exe
          if-no-files-found: error
