name: Main workflow

on: [ push ]  

env:
  TONOS_SE_OWNER: tonlabs
  TONOS_SE_REPO: tonos-se
  TONOS_SE_VERSION: 0.25.0
  ARANGODB_VERSION: 3.7.9
jobs:
  build-node:
    env: 
      PUBLISH_FOLDER: node
    name: Build Node SE ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: 🏃 Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TONOS_SE_OWNER }}/${{ env.TONOS_SE_REPO }}
          ref: ${{ env.TONOS_SE_VERSION }}

      - name: 'Tar files'
        run: |
          mkdir -p ${{ env.PUBLISH_FOLDER }}
          touch ${{ env.PUBLISH_FOLDER }}/test.txt
          tar -cvf node-${{ matrix.os }}.tar ${{ env.PUBLISH_FOLDER }}

      - name: 📚 Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-${{ matrix.os }}
          path: node-${{ matrix.os }}.tar
          if-no-files-found: error  

  build-arango:
    env:
      PUBLISH_FOLDER: arangodb      
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ubuntu-latest
    steps:
        - name: Checkout current repo
          uses: actions/checkout@v2

        - name: Load parameters
          uses: actions/github-script@v3.1.0
          with:
            script: |
              const config = require(`${process.env.GITHUB_WORKSPACE}/config.arangodb.js`)(`${process.env.ARANGODB_VERSION}`)
              core.exportVariable('PATH_IN_ARCHIVE', config["${{ matrix.os }}"].pathInArchive)
              core.exportVariable('URL', config["${{ matrix.os }}"].url)

        - name: Download and unpack
          uses: nrukavkov/configurator@v0.0.8
          with:
            name: "arangodb"
            url: ${{env.URL}}
            pathInArchive: ${{env.PATH_IN_ARCHIVE}}

        - name: Checkout tonos-se
          uses: actions/checkout@v2
          with:
            path: tonos-se
            repository: 'tonlabs/tonos-se'
        
        - name: Create structure and copy additional files
          run: |
            mv .configurator/arangodb ./${{ env.PUBLISH_FOLDER }}
            mkdir -p ${{ env.PUBLISH_FOLDER }}/var/lib/arangodb3-apps
            mkdir -p ${{ env.PUBLISH_FOLDER }}/var/lib/arangodb3
            cp -r tonos-se/docker/arango/initdb.d ${{ env.PUBLISH_FOLDER }}/initdb.d
        
        - name: 'Tar files'
          run: tar -cvf arangodb-${{ matrix.os }}.tar ${{ env.PUBLISH_FOLDER }}

        - name: 📚 Publish artifact
          uses: actions/upload-artifact@v2
          with:
            name: arangodb-${{ matrix.os }}
            path: arangodb-${{ matrix.os }}.tar
            if-no-files-found: error  
  
  prepare-artifacts:
    needs:
      - build-node
      - build-arango
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: 🎣 Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts        
        
      - name: 'Merge tar files'
        working-directory: artifacts
        run: |
          declare -a arr=("ubuntu" "windows" "macos")
          for i in "${arr[@]}"
          do
            echo "Creating archive release-$i.tar.gz"
            ls **/arangodb-$i.tar
            ls **/node-$i.tar
            tar --concatenate --file=release-$i.tar arangodb-$i/arangodb-$i.tar
            tar --concatenate --file=release-$i.tar node-$i/node-$i.tar
            gzip release-$i.tar
          done
           
      - name: 📚 Publish artifact
        uses: actions/upload-artifact@v2
        with:          
          name: release
          path: artifacts/release-*.tar.gz
          if-no-files-found: error

  publish:
    name: Create Release
    runs-on: ubuntu-latest  
    needs:
      - prepare-artifacts
    steps: 
      - name: 🎣 Download release artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
          name: release
   
      - name: 🍸 Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.TONOS_SE_VERSION }}"
          prerelease: false
          title: "Node SE binaries ${{ env.TONOS_SE_VERSION }}"
          files: artifacts/**/release-*.tar.gz