name: Main workflow

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  TONOS_SE_REPO: tonlabs/tonos-se

jobs:
  build-node:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]

    runs-on: ${{ matrix.os }}-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: 🏃 Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TONOS_SE_REPO }}

      - name: ⚡ Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ton-node-se/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('ton-node-se/Cargo.toml') }}

      - name: 🔨 Build
        working-directory: ton-node-se
        run: |
          cargo build --release

      - name: 🐳 Publish
        uses: actions/upload-artifact@v2
        with:
          name: ton_node_startup-${{ matrix.os }}
          path: |
            ton-node-se/target/release/ton_node_startup
            ton-node-se/target/release/ton_node_startup.exe
          if-no-files-found: error
