name: Main workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest

    defaults:
      run:
        working-directory: ton-node-se

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tonlabs/tonos-se

      # - name: Prepare Linux
      #   if: ${{ matrix.os == 'ubuntu'}}
      #   working-directory: ton-node-se
      #   run: |
      #     sudo apt update && sudo apt install -y cmake pkg-config libssl-dev
      #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

      # - name: Prepare MacOS
      #   if: ${{ matrix.os == 'macos'}}
      #   working-directory: tonos-se/ton-node-se
      #   run: |
      #     brew cask install cargo
      #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

      # - name: Prepare Wrindows
      #   if: ${{ matrix.os == 'windows'}}
      #   working-directory: tonos-se/ton-node-se
      #   run: |
      #     sudo apt update && sudo apt install -y cmake pkg-config libssl-dev
      #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

      - name: Build
        run: |
          cargo build --release
